### ISSUE TITLE
Reward every lick doesn't work. 

### ISSUE THREAD

**Issue by alessli** [Gavin-Perry/OdorChoice#38]
i turned it on during a trial a 4 0 R, if clik on the left nothing happens, if i lick on the right it gives me 4 reward every time i lick (and MR# = 1). And when reward all licks is on, and repeat until correct is on, even if i lick on the R during CWT, the task doesn't go to the next trial.

**Comment by Gavin-Perry** [comment]
You are correct. Reward Every didn't account for pretrial setting or when a reward was set to 0
This has been corrected in ML 2.8 (and corresponding Pico version). MR value is only used if the Reward setting was 0 otherwise the existing setting is left as is. Either use RwEv outside of trials, or set rewards to 1, or say how you need it,  or be happy as is.

Second issue of RewAll AND RepCor needs to be investigated. I understand that these are related issues but in general one issue per issue '#

**Comment by Gavin-Perry** [comment]
Reward all licks works better including updating lick count when MR# is changed.
With RewEvery during trials it gets complicated as I don't know how many rewards to give.
Give the MR# or the trial based number of rewards. Currently it's trial based so if there is air it won't reward that. REALLY messy if you want it different. Check how it runs for your experiments as you need and let me know here.

**Comment by Gavin-Perry** [comment]
Fixed in v29 please check and reopen issue if there is still a problem

**Comment by alessli** [comment]
Seems to be working. 
Concerning your question, one drop per lick.

**Comment by alessli** [comment]
Where is the minimum inter reward interval coming from? In the early training phases, I am not sure it will be fast enough.

**Comment by Gavin-Perry** [comment]
I think that is a setable parameter but I'm not sure where. I think it's 20 milliseconds. But the limit is actually the time it takes to deliver the reward and have that time out so you've got that set to 150. 
That would be the H parameter, which you can set in the load defaults file but doesn't have anything on the GUI since it wasn't supposed to change much.
You can change the number of rewards per lick with the spinner next to manual rewards.

**Comment by alessli** [comment]
Few issues.
1. If reward every lick is on, no other lick is detected during reward delivery and time out. can this be fixed?
2.  I am licking repeatedly on the same side, but i can't get below ~1200 ms. i clearly hear the connector touching the licking port, but the lick is not registered. do you know why? This doesn't happen when licking every reward is off ( i can get licks in 90 ms).
3. Last,  increasing the number of rewards per lick may work in some situation but not all of it. It is possible that 150 ms is ok (and it should be), but i need to test it with that speed first.

**Comment by Gavin-Perry** [comment]
This should be fixed in v30 
I've added the drop delay parameter and adjusted to skip extra delays. Let me know if it is working now.

**Comment by alessli** [comment]
it seems to be working ok.
