### ISSUE TITLE
Error after manually changing the list into AA trial.

### ISSUE THREAD

**Issue by alessli** [Gavin-Perry/OdorChoice#50]
Paused a session, started an 'all new', used same list:
 	1	4	0
	1	3	1
   then changed manually on the gui: to :
	2	3	-2
	1	3	1
  started the first trial (3 -2 L), and system crashed.
 On the command windows I had the following error: 
	Error using indexing
	The specified key is not present in this container.

	Error in MouseOdor30/StartTrial (line 703)
    	app.xBin = app.xMap(xStr);

	Error in MouseOdor30/RunOneTrial (line 739)
    	StartTrial(app,TNum);  % Formerly misnamed RunTrial v2x; Sets TrialRunning true

	Error in MouseOdor30/DoSession (line 801)
        RunOneTrial(app,trlNumber); % run one (do while)

	Error in MouseOdor30/StatusButtonPushed (line 2105)
                    DoSession(app,1);  % Go run this session

	Error in matlab.apps.AppBase>@(source,event)executeCallback(ams,app,callback,requiresEventData,event) (line 62)
            newCallback = @(source, event)executeCallback(ams, ...
 
	Error while evaluating Button PrivateButtonPushedFcn.

**Comment by Gavin-Perry** [comment]
Because the there were no 3 -2 trials in your original list. The error is correct:

The specified key is not present in this container.
Error in MouseOdor30/StartTrial (line 703)
	app.xBin = app.xMap(xStr);      
**Map the reward drops to the graph**

It's not recommended to manually edit the Trial List, especially not to add a trial type that was not in the original list as it can't be put onto the graph. :-(

BTW, you only need to include the first line or 2 of the error trace back. I generally know where e.g. line 703 is called from.  At the Start of a trial I check which bin of the B-A choice the result will go to. No bin for the new 3 -2  presentation.

**Comment by alessli** [comment]
ok, thanks.

**Comment by Gavin-Perry** [comment]
No, no numbers can change -3 2 can't even change to a 2 -3 as that's a different column in the graph
