### ISSUE TITLE
Problem with the bar plot on v31.

### ISSUE THREAD

**Issue by alessli** [Gavin-Perry/OdorChoice#55]
When I use the list below everything works.
1	5	-2
1	4	0
1	4	1
1	3	2
1	2	5
1	-1	8
1	0	5
1	0	3

But, when i add the following trial type [1 2 5] I get the errors below:
![image](https://github.com/user-attachments/assets/7e50b926-e9e1-4cfd-bee6-6bcc4c8035ac)

![image](https://github.com/user-attachments/assets/c6dbd641-5e3f-4fd5-94c2-6008a100cc83)

**Comment by Gavin-Perry** [comment]
Similar to #50 
You shouldn't include the same trial type multiple times in the same trial list. You already had 1 2 5 in your list, so you should just change it to 2 2 5 rather than adding the same numbers again. I can add code to allow you to make this mistake if you want, but it's complicated as you don't want multiple 2-5 bins in the graph.  Each trial type should be listed only once.

_I'll leave this open for your reply._

**Comment by alessli** [comment]
No, you are right. Let's keep it this way.
