### ISSUE TITLE
Not all values are initialized with a new session

### ISSUE THREAD

**Issue by alessli** [Gavin-Perry/OdorChoice#67]
I was running a session using 'rewards ever lick'. I ended the session by closing the window. Opened a new one by launching 'MouseOdorXX', the GUI was showing that reward every lick was OFF, but the animal was rewarded every lick until I clicked on 'reward every lick off'.

**Comment by Gavin-Perry** [comment]
Initializing MATLAB didn't restart the Pico. You could always hit the run reset button or I can come up with a software way to reinitialize everything. But some times with a new session you just want to repositioning nozzles or change animals and continue with the same parameters. Let's work on a flow chart of what happens when.

**Comment by alessli** [comment]
Sure, indeed I am not against parameters not being reset. My main 'concern' is the inconsistency between what the GUI showed and the actual pico setting. What can I work on  on the flow chart?

**Comment by Gavin-Perry** [comment]
Make a chart of what you want to happen at each state change

Sent via the Samsung Galaxy S22 5G, an AT&T 5G smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by alessli** [comment]
init Pico to params in LoadDefaults.txt  parameter file when starting ML

**Comment by Gavin-Perry** [comment]
I have updated to load params to Pico in v44 but it occurs to me looking at the code that I can just update parameters you want to set if there are values you might want to keep from earlier session. Using r command I could even set MatLab to be the same as Pico instead of the other way around. Not something to do now, I just wanted you to know it's possible.

**Comment by Gavin-Perry** [comment]
Pico updates at ML restart
