### ISSUE TITLE
Reward calibration and reward table

### ISSUE THREAD

**Issue by alessli** [Gavin-Perry/OdorChoice#68]
I did some calibration (using commands a200 and c200, ie a left and right). Although the juice was the same, the lines yielded results consistently 20-30%  different. 
We definitely an input file (4 rows by 5 columns) with time in ms used a correction. So for each line and each level, the U time will be corrected by adding the value indexed in the input file.

And we also need a calibration software to test if the average amount for each line, each level. Essentially, we need a software that gives a N amount of rewards, spaced in time by a long time T (every  2 second, for example), but with the each reward being a pulse of j single rewards spaced by 150 ms (where j is an input).

**Comment by Gavin-Perry** [comment]
Agreed. I will work on a calibration mode program. There is still plenty of room in the Pico memory so we can have commands to start different modes. 
Calibration mode 
Training mode 
Session mode 
Anything else?

**Comment by alessli** [comment]
Great. No those are the 3 modes we need.

**Comment by alessli** [comment]
I just realized that a 'cleaning mode' would be very useful. A mode where we could switch and keep on multiple reward lines at the same time. Right now flashing the juices take ~5-10 mins.

**Comment by Gavin-Perry** [comment]
The switches will take care of the cleaning mode though actually there is a cleaning mode already. I think it's v1000 but not well documented.
Table for rewards as you tell it takes care of an offset but not non-linearity.  Rather than an offset, the table can have the actual duration needed for a drop of the desired size. If that were to change you would just load a different table.

**Comment by Gavin-Perry** [comment]
All completed in v50 with separate Valve Open Times for each reward.
